project_id = "upzjnifdcmevsdfmzwzw"

[functions.ping]
verify_jwt = false

[functions.webhook-comments]
verify_jwt = false

[functions.webhooks-gupshup]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.add-to-waitlist]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.simulate-comment]
verify_jwt = false