name: Audit Report

on:
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run TypeScript check
        run: npm run build
        
      - name: Run linting
        run: npm run lint
        
      - name: Generate audit report
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: npm run audit:report
        continue-on-error: true
        
      - name: Upload audit artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: audit-report
          path: |
            tmp/audit/report.md
            tmp/audit/scan.json
            tmp/audit/usage.json
            docs/cleanup/plan.md
            docs/cleanup/sql/
          retention-days: 30
          
      - name: Comment PR with audit summary
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            try {
              const reportPath = 'tmp/audit/report.md';
              if (fs.existsSync(reportPath)) {
                const report = fs.readFileSync(reportPath, 'utf8');
                const summary = report.split('\n').slice(0, 20).join('\n');
                
                await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: `## 🔍 Audit Report Summary

${summary}

...

📋 **Full report and cleanup plan available in PR artifacts**

*This is an informational report and does not affect PR status.*`
                });
              }
            } catch (error) {
              console.log('Could not post audit summary:', error.message);
            }